### ISSUE TITLE
Default value for inserts vs CREATE POLICY ... WITH CHEC

### ISSUE THREAD

**Issue by PeterKneale** [bytefish/AspNetCoreMultitenancy#1]
Thanks for the good blog post on this but i am curious about having the tenant set via a default value?

```
... sql tenant_name VARCHAR(255) NOT NULL DEFAULT current_setting('app.current_tenant')::VARCHAR
```

I think the above would mean if the application supplied the wrong tenant (overriding the default value), it would be accepted by the table, while with the below it wouldn't.

```
CREATE POLICY tenant_customer_isolation_policy ON sample.customer
    USING (tenant_name = current_setting('app.current_tenant')::VARCHAR)
   WITH CHECK (tenant_name = current_setting('app.current_tenant')::VARCHAR);
```

>> A policy grants the permission to select, insert, update, or delete rows that match the relevant policy expression. Existing table rows are checked against the expression specified in USING, while new rows that would be created via INSERT or UPDATE are checked against the expression specified in WITH CHECK.

**Comment by bytefish** [comment]
Do you think this should be added to the article? I could add it. I have taken the repository for the website private, because of not wanting deleted articles being public (for now).

**Comment by PeterKneale** [comment]
I'm still trying to decipher the postgres documentation but now i'm thinking what you have is right 
> For policies that can have both USING and WITH CHECK expressions (ALL and UPDATE), if no WITH CHECK expression is defined, then the USING expression will be used both to determine which rows are visible (normal USING case) and which new rows will be allowed to be added (WITH CHECK case).
